sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: FecVsfX0rtihU3lparEch9RWEpdLsk8+doXdLOpEE6k0lyeJnclQc4yLFc1ZTwL3YOOFPs5XEpw7EOk9p+hcY6wO4ozNn3UegSVIDX1iLTOEGy3rWp+Ac6uZjSaJibQmnx+5e/fbV0dmJxOZUH8Wq+oP38uNeESZLyGVZlxp2cJRZOd2f3DgaKlxmBLUJCBjQUEV73UYD+zZEgO673Jnmp83a9BeadkGKmDSCDvZu1Q9FTbLafCwZs0AbYVY+Hel3JNSuRW3LS6BMcIwNrgQ+oLdLZaXcGphOKBYonbKDoFGKaJpkHtluRSPsbwKdcJxwo1gcKeWWgvlT+Ym2UA5ARYmgl1s527v3PNLYFV3q79RDfkd0gb8ZbTyWKcOAqJXdXGCQTfc9LSNHn0O7MhwreEIc6ominaGOlSoh1qlfD6FM7uf53ZJsZPD87kaAPfpZA1B1rQ9sbKNP8qlRFzqUkNI3sbpYEFoBq0iK42CHbEDrR8zDT1X9GSwLzMTxvL5oKUlbT/BhoyRsjPuE2hqQfGtQiy2dHT43QTuNRgC/uD8mSK6HmzpcjJ0lH0aYsLDtKBagG0V5JN2YGzl8oIICvkJuKS2JNjthEenBtLA7vrakOT6R22hWJdkUnGDK0/E/liyrl9lXcjJ2PEAedZxgvM1q9ZI25eWvV6eqPk/Y3w=
  - secure: fY3VBYi+fM1TO3pQ0bBejN42gzafBWsUbysHUB6feuK1lNAkEW6yobhuCc5zDd+DSOOXf6GwBkNHiQoei6v5/B0X5qGf6SwIHtcp5THWplVIqQ9c5+Ka59NqBvYVBOwXZXyEgzp+MIgfM3eJKBBiSIEe4oEJkTqt+zHbcSSS7nCOPmRihjV7yg4E9fwb5U0v5lAtYBAdh6TRfgA7nymTiNKvE3VFg0kNacE7mAIjxzMr9mhmhKdqLIOd65yoKoiPlmqYT6XZ1P5eourpVtppKtiWo/p5l5EWOkh5Mc7ozVIOOvcoepb1h+/AQ4bNqpabUSWQ/wizenKtQTM94tAfxD7Hbk9yKJnptUsRrbcvMbrd97ytGE82k3yDuw+YpE92KAUYB/4UW1Pf5h9ApFdsMU5DrHsI1bXOHK/R7a7GCP9fD0VAACvR3i6DygJujGXceHjz0jEiRoqrf+tl5oCX3s6rf6DH5OEsZtbeKOZ4cxcrD9FNQbyoe6+mJ/5HDTuoIoKiZEJ23Q2akBf/DQsWilFv4JLp8BOE5pk7IpecdMHo6JeM2BSoW3Quky3NB/FHSN1eTtm174+7i4RVSX/EYFARfEZTuS4hXkW5k+AS9Ak/OK/MZRwVmVv9qHtUQRVLoO1lasINEusIyLl38faFTnOCOSdg2EDTV3dMjTcRn6E=
